dnsChallenge LAN changes
alex3305/hassio-addons pull request #12
Opened 2020-09-17 13:56 UTC by leakypixel

While using this addon to make a dnsChallenge certificate request, I ran into a couple of issues relating to DNS on my LAN not mirroring that of the public internet, as well as special characters in API keys. 

In order to make this work for me, I had to make a couple of changes to allow escape characters in env vars, and add delayBeforeCheck and resolvers to the generated traefik static config.

I also tidied up a little around the previous PR I made, by adding the references to aarch64 in the config and build files.

2020-09-18 20:03 UTC, alex3305 requested changes
Great changes! Thanks for that. I have some small review comments I would like to iron out before merging.

I would also like to see some documentation on the new parameters within the [Readme](README.md) file.

2020-09-18 20:03 UTC, alex3305 commented on traefik/traefik.yaml.j2
> +        {% endfor %}
Please remove the empty line and you can add an `-` to the `endfor` within the yaml loop to keep it all neatly tight together.

```suggestion
        {%- endfor %}
```

2020-09-21 11:43 UTC, leakypixel commented on traefik/config.json
> +    "arch": [
No problem - to be honest I didn't make this change deliberately, I'll make these changes now :)

2020-09-21 12:02 UTC, leakypixel commented
I believe that's the changes done - apologies for the reformatting, it was a complete oversight. 

Thanks for taking the time to review this, let me know if there're any other changes required :)

2020-09-23 09:47 UTC, merged

2020-09-23 09:47 UTC, alex3305 commented
Thanks for the changes you have made. I have accepted your PR.

When I requested additional documentation I thought that the docs were still in the [Readme](README.md), but I forgot that they were moved to the [Docs](DOCS.md) file. I will move them for you. I will also update the add-on version, so your changes will be available through an update of this add-on.

Thanks again for your contribution and the nice collaboration!